source 'https://rubygems.org'
gem 'cucumber'
gem 'capybara'
gem 'rspec-expectations'
gem 'poltergeist', ">= 1.4.0"
gem 'selenium'
gem 'selenium-webdriver', '2.43.0'
gem 'launchy'
gem 'rest-client'
gem 'curb'
gem 'fivemat'
gem 'parallel_tests'
gem 'debugger-ruby_core_source'
gem 'pry', '~> 0.10.1'
gem 'pry-debugger', '~> 0.2.3'
gem 'pry-remote', '~> 0.1.8'